/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      screens: {
        xs: "390px",
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1536px",
      },
      colors: {
        landing: {
          background: "oklch(0.97 0.005 100)",
          foreground: "oklch(0.18 0.01 100)",
          muted: "oklch(0.93 0.005 100)",
          "muted-foreground": "oklch(0.45 0.01 100)",
          surface: "oklch(0.94 0.005 100)",
          accent: "oklch(0.55 0.12 155)",
          "accent-foreground": "oklch(0.98 0 0)",
          border: "oklch(0.88 0.005 100)",
        },
        "tertiary": "#1c2b4b",
        "on-primary": "#ffffff",
        "pro-badge-text": "#9A3412",
        "error": "#ba1a1a",
        "secondary-container": "#fe8933",
        "tertiary-fixed-dim": "#b8c6ef",
        "on-secondary-fixed": "#321300",
        "inverse-primary": "#aec6ff",
        "primary": "#002a61",
        "on-background": "#0d1c2d",
        "primary-container": "#003f8c",
        "secondary-fixed-dim": "#ffb689",
        "outline": "#737782",
        "primary-fixed-dim": "#aec6ff",
        "inverse-on-surface": "#e9f1ff",
        "bg-light": "#F8FAFC",
        "gold-badge-text": "#92400E",
        "silver-badge-text": "#475569",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#0a1a3a",
        "on-secondary-fixed-variant": "#743500",
        "on-secondary": "#ffffff",
        "inverse-surface": "#233143",
        "error-red": "#EF4444",
        "surface-dim": "#ccdbf2",
        "female-badge-text": "#9D174D",
        "border-light": "#E2E8F0",
        "secondary-fixed": "#ffdbc8",
        "accent-gold": "#FFD447",
        "silver-badge-bg": "#E2E8F0",
        "verified-badge-bg": "#DCFCE7",
        "surface-container-highest": "#d4e4fa",
        "surface-container-high": "#dbe9ff",
        "surface-container-low": "#eef4ff",
        "error-container": "#ffdad6",
        "secondary": "#984800",
        "pro-badge-bg": "#FFE4CC",
        "tertiary-container": "#334163",
        "on-surface": "#0d1c2d",
        "surface-bright": "#f8f9ff",
        "female-badge-bg": "#FCE7F3",
        "on-secondary-container": "#652e00",
        "surface-variant": "#d4e4fa",
        "on-tertiary": "#ffffff",
        "background": "#f8f9ff",
        "on-primary-fixed-variant": "#0b4491",
        "outline-variant": "#c3c6d3",
        "gold-badge-bg": "#FEF3C7",
        "on-primary-container": "#87aeff",
        "on-surface-variant": "#434751",
        "primary-fixed": "#d8e2ff",
        "on-tertiary-fixed-variant": "#384668",
        "surface-tint": "#2f5caa",
        "verified-badge-text": "#166534",
        "surface-container": "#e5efff",
        "on-tertiary-container": "#9faed5",
        "on-primary-fixed": "#001a42",
        "success-green": "#22C55E",
        "surface": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "tertiary-fixed": "#d9e2ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "role-card": "20px"
      },
      fontFamily: {
        h1: ["Sora", "sans-serif"],
        h2: ["Sora", "sans-serif"],
        h3: ["Sora", "sans-serif"],
        body: ["Inter", "sans-serif"],
        small: ["Inter", "sans-serif"],
        caption: ["Inter", "sans-serif"],
        button: ["Inter", "sans-serif"],
      },
      fontSize: {
        h1: ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h1-mobile": ["30px", { lineHeight: "1.2", fontWeight: "700" }],
        h2: ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        h3: ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        body: ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        small: ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "small-bold": ["14px", { lineHeight: "1.5", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        button: ["14px", { lineHeight: "24px", fontWeight: "600" }],
      },
      spacing: {
        "card-padding": "20px",
        "btn-h-padding": "24px",
        "btn-v-padding": "14px",
        "unit": "4px",
        "gutter": "24px",
        "container-margin-mobile": "16px",
        "input-h-padding": "16px",
        "container-margin-desktop": "40px",
        "input-v-padding": "14px"
      }
    },
  },
  plugins: [],
}
